import 'package:arth/providers/paycheck_provider.dart';
import 'package:arth/providers/user_profile_provider.dart';
import 'package:arth/screens/s29_paycheck_shell_screen.dart';
import 'package:arth/screens/s30_tax_plan_entry_screen.dart';
import 'package:arth/theme/app_theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';

void main() {
  test('manual evidence is kept for review and leaves sample mode', () {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    container
        .read(paycheckProvider.notifier)
        .addEvidence('Cult gym receipt July.pdf');
    final paycheck = container.read(paycheckProvider);

    expect(paycheck.usingSampleData, isFalse);
    expect(paycheck.evidence.first.name, 'Cult gym receipt July.pdf');
    expect(paycheck.evidence.first.statusLabel, 'REVIEW');
    expect(paycheck.evidence.first.needsAction, isTrue);
  });

  testWidgets('tax planning opens as a contained tool from You',
      (tester) async {
    tester.view.physicalSize = const Size(390, 844);
    tester.view.devicePixelRatio = 1;
    addTearDown(() {
      tester.view.resetPhysicalSize();
      tester.view.resetDevicePixelRatio();
    });

    final router = GoRouter(
      initialLocation: '/paycheck/you',
      routes: [
        GoRoute(
          path: '/paycheck/you',
          builder: (_, __) => const PaycheckShellScreen(initialIndex: 3),
        ),
        GoRoute(
          path: '/tax-plan',
          builder: (_, __) => const TaxPlanEntryScreen(),
        ),
      ],
    );
    addTearDown(router.dispose);

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          completedTaxProfileProvider.overrideWith((ref) async => false),
        ],
        child: MaterialApp.router(
          theme: AppTheme.light,
          routerConfig: router,
        ),
      ),
    );
    await tester.pumpAndSettle();

    await tester.scrollUntilVisible(
      find.byKey(const Key('tax_plan_tool')),
      300,
      scrollable: find.byType(Scrollable).first,
    );
    await tester.tap(find.byKey(const Key('tax_plan_tool')));
    await tester.pumpAndSettle();

    expect(find.text('Plan your tax.'), findsOneWidget);
    expect(find.text('Income'), findsOneWidget);
    expect(find.text('Housing'), findsOneWidget);
    expect(find.text('Deductions'), findsOneWidget);
    expect(find.byKey(const Key('tax_plan_start')), findsOneWidget);
    expect(find.textContaining('not generated by AI'), findsOneWidget);
    expect(tester.takeException(), isNull);
  });

  testWidgets('closing tax planning returns to the paycheck profile',
      (tester) async {
    final router = GoRouter(
      initialLocation: '/tax-plan',
      routes: [
        GoRoute(
          path: '/tax-plan',
          builder: (_, __) => const TaxPlanEntryScreen(),
        ),
        GoRoute(
          path: '/paycheck/you',
          builder: (_, __) => const PaycheckShellScreen(initialIndex: 3),
        ),
      ],
    );
    addTearDown(router.dispose);

    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          completedTaxProfileProvider.overrideWith((ref) async => false),
        ],
        child: MaterialApp.router(
          theme: AppTheme.light,
          routerConfig: router,
        ),
      ),
    );
    await tester.pumpAndSettle();
    await tester.tap(find.byKey(const Key('tax_plan_close')));
    await tester.pumpAndSettle();

    expect(find.text('YOUR PAY PROFILE'), findsOneWidget);
    expect(find.text('Small tools'), findsOneWidget);
  });
}
