import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../providers/user_profile_provider.dart';
import '../theme/app_theme.dart';
import '../theme/paycheck_theme.dart';
import '../widgets/premium_ui.dart';

class TaxPlanEntryScreen extends ConsumerWidget {
  const TaxPlanEntryScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final complete = ref.watch(completedTaxProfileProvider);

    return Scaffold(
      backgroundColor: PaycheckColors.canvas,
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(20, 16, 20, 28),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  IconButton(
                    key: const Key('tax_plan_close'),
                    tooltip: 'Back to paycheck',
                    onPressed: () => context.go('/paycheck/tax'),
                    icon: const Icon(Icons.close_rounded),
                    color: PaycheckColors.ink,
                  ),
                  const Spacer(),
                  Text('Tax plan', style: PaycheckType.utility()),
                ],
              ),
              const SizedBox(height: 28),
              Container(
                width: 48,
                height: 48,
                decoration: const BoxDecoration(
                  color: PaycheckColors.contractSoft,
                  borderRadius: AppRadius.card,
                ),
                child: const Icon(
                  Icons.calculate_outlined,
                  color: PaycheckColors.contract,
                ),
              ),
              const SizedBox(height: 20),
              Text('Plan your tax', style: PaycheckType.title()),
              const SizedBox(height: 12),
              Text(
                'Compare both regimes and see your deduction gaps.',
                style: PaycheckType.body(color: PaycheckColors.inkSoft),
              ),
              const SizedBox(height: 28),
              const _TaxChapter(
                number: '01',
                title: 'Income',
                detail: 'Annual income and employment type',
                color: PaycheckColors.contract,
              ),
              const _TaxChapter(
                number: '02',
                title: 'Housing',
                detail: 'City, rent, HRA and home loan',
                color: PaycheckColors.matched,
              ),
              const _TaxChapter(
                number: '03',
                title: 'Deductions',
                detail: '80C, NPS, insurance and education loan',
                color: PaycheckColors.pending,
              ),
              const _TaxChapter(
                number: '04',
                title: 'Your result',
                detail: 'Regime comparison and ranked tax gaps',
                color: PaycheckColors.claim,
                last: true,
              ),
              const SizedBox(height: 24),
              complete.when(
                loading: () => const ArthLoadingPanel(
                  title: 'Checking your diagnostic',
                  insights: ['Looking for saved answers.'],
                ),
                error: (_, __) => const _TaxActions(complete: false),
                data: (isComplete) => _TaxActions(complete: isComplete),
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: PaycheckColors.paper,
                  borderRadius: BorderRadius.circular(AppRadius.sm),
                  border: Border.all(color: PaycheckColors.line),
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Icon(
                      Icons.verified_user_outlined,
                      color: PaycheckColors.matched,
                      size: 21,
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        'Calculated by ARTH rules, not generated by AI.',
                        style: PaycheckType.body(
                          color: PaycheckColors.inkSoft,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _TaxActions extends StatelessWidget {
  final bool complete;

  const _TaxActions({required this.complete});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        FilledButton(
          key: const Key('tax_plan_start'),
          style: FilledButton.styleFrom(
            minimumSize: const Size.fromHeight(56),
            backgroundColor: PaycheckColors.ink,
            foregroundColor: Colors.white,
            shape: const RoundedRectangleBorder(
              borderRadius: AppRadius.control,
            ),
          ),
          onPressed: () => context.push('/tax-plan/questions'),
          child: Text(
            complete ? 'Update my answers' : 'Start tax diagnostic',
            style: PaycheckType.bodyStrong(color: Colors.white),
          ),
        ),
        if (complete) ...[
          const SizedBox(height: 8),
          TextButton(
            key: const Key('tax_plan_view_result'),
            onPressed: () => context.push('/tax-plan/results'),
            child: Text(
              'View current result',
              style: PaycheckType.bodyStrong(
                color: PaycheckColors.contract,
              ),
            ),
          ),
        ],
      ],
    );
  }
}

class _TaxChapter extends StatelessWidget {
  final String number;
  final String title;
  final String detail;
  final Color color;
  final bool last;

  const _TaxChapter({
    required this.number,
    required this.title,
    required this.detail,
    required this.color,
    this.last = false,
  });

  @override
  Widget build(BuildContext context) {
    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          SizedBox(
            width: 38,
            child: Column(
              children: [
                Container(
                  width: 30,
                  height: 30,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: color,
                    shape: BoxShape.circle,
                  ),
                  child: Text(
                    number,
                    style: PaycheckType.utility(color: Colors.white),
                  ),
                ),
                if (!last)
                  Expanded(
                    child: Container(width: 2, color: PaycheckColors.line),
                  ),
              ],
            ),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.only(bottom: 20),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(title, style: PaycheckType.bodyStrong()),
                  const SizedBox(height: 4),
                  Text(
                    detail,
                    style: PaycheckType.body(color: PaycheckColors.inkSoft),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
